version: '3.7'

services:
  zhasa-news:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=psql://zhassapp:zhassapp@postgres:5432/zhassapp
networks:
  default:
    external:
      name: zhassapp_default

volumes:
  pgdata:
  dmedia:
  dstatic: