

CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(64) NOT NULL,
	second_name VARCHAR(64) NOT NULL
);


CREATE TABLE posts(
	id SERIAL PRIMARY KEY,
	title VARCHAR(256) NOT NULL,
	body TEXT NOT NULL,
	user_id INT REFERENCES users(id) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE comments(
	id SERIAL PRIMARY KEY,
	body TEXT NOT NULL,
	user_id INT REFERENCES users(id) NOT NULL,
	post_id INT REFERENCES posts(id) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
