// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateOrUpdateUser(ctx context.Context, arg CreateOrUpdateUserParams) (User, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DeleteComment(ctx context.Context, id int32) error
	DeletePost(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	// Example queries for sqlc
	GetCommentById(ctx context.Context, id int32) (Comment, error)
	GetCommentsAndAuthorsByPostId(ctx context.Context, postID int32) ([]GetCommentsAndAuthorsByPostIdRow, error)
	// Example queries for sqlc
	GetPostById(ctx context.Context, id int32) (Post, error)
	GetPostsAndPostAuthors(ctx context.Context, arg GetPostsAndPostAuthorsParams) ([]GetPostsAndPostAuthorsRow, error)
	// Example queries for sqlc
	GetUser(ctx context.Context, id int32) (User, error)
	ListPosts(ctx context.Context) ([]Post, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
